apps/api-gateway/src/module.api/users.controller.ts, apps/orders-service/src/test/orders.controller.spec.ts, apps/users-service/src/__mocks__/users-service.service.ts, apps/users-service/src/test/e2e/users.e2e.ts, apps/users-service/src/test/stubs/user.stub.ts, apps/users-service/src/test/users.controller.spec.ts, apps/users-service/src/users-service.controller.ts, apps/users-service/src/users-service.service.ts, libs/common/src/database/schemas/users.schema.ts, libs/common/src/database/types/common.ts, libs/common/src/dto/UpdateUserDto.ts, package.json
=> feature(user-service): login on signup

apps/api-gateway/src/module.api/listing.controller.ts, apps/listings-service/src/listings.controller.ts, apps/listings-service/src/listings.service.ts, apps/vendors-service/src/vendors.service.ts, libs/common/src/database/abstract.repository.ts, libs/common/src/database/types/common.ts, packages/sticky/libs/common/src/schemas/index.ts, packages/sticky/package.json
=> feature(app): updated vendor and listing for users

apps/vendors-service/src/vendors.service.ts, libs/common/src/database/schemas/order.schema.ts, libs/common/src/database/types/common.ts, libs/common/src/dto/PlaceOrder.dto.ts, libs/common/src/typings/Global.Interface.ts, packages/sticky/libs/common/src/schemas/index.ts, packages/sticky/libs/common/src/typings/index.ts
=> feature(app): allow multiple listings order + added settings to vendors user

libs/common/src/database/dto/user/address.book.dto.ts, packages/sticky/package.json
=> fix(address-book): added labelname to createAddressBook DTO

apps/api-gateway/src/module.api/address-book.controller.ts, apps/listings-service/src/listings.service.ts, apps/orders-service/src/orders-service.service.ts, apps/payment-service/src/charge/charge.service.ts, libs/common/src/database/schemas/address.book.schema.ts, libs/common/src/database/schemas/order.schema.ts, libs/common/src/database/schemas/payment.schema.ts, libs/common/src/dto/PlaceOrder.dto.ts, packages/sticky/libs/common/src/schemas/index.ts, packages/sticky/libs/common/src/typings/index.ts
=> fix(app): order quantity and sticky types update

apps/listings-service/src/listings.module.ts, apps/notification-service/src/notification-service.module.ts
=> fix(app): wrong module imports in notification and listing service

apps/notification-service/src/subscription.controller.ts, apps/notification-service/src/subscription.service.ts, apps/vendors-service/src/vendors.service.ts, libs/common/src/dto/subscription.dto.ts
=> feature(vendor-service, notification-service): Add push notification on vendor's account approval

apps/admin-gateway/src/module.api/admin.controller.ts, apps/admin-service/src/admin-service.controller.ts, apps/admin-service/src/admin-service.service.ts, libs/common/src/typings/QUEUE_MESSAGE.ts
/kind feature
This PR creates the reset password feature for admin users in `admin-gateway`.
Fixes #
=> feature(admin): admin users reset password endpoint in admin gateway

apps/admin-gateway/src/module.api/admin.controller.ts, apps/admin-service/src/admin-service.controller.ts, apps/admin-service/src/admin-service.service.ts, libs/common/src/typings/QUEUE_MESSAGE.ts
/kind fix
This PR resolves the `getAllAdmins` query to fetch from newest to oldest.
Fixes #
=> fix(admin): get all admins sorted in desc order

apps/users-service/src/users-service.controller.ts
/kind fix
This  PR corrects the get user queue message from `GET_USER_JWT` to `GET_USER`.
Fixes #
=> fix(admin): fix queue message to get a single user by id

apps/admin-gateway/src/module.api/dashboard.controller.ts, apps/users-service/src/users-service.controller.ts, apps/vendors-service/src/vendors.controller.ts, apps/vendors-service/src/vendors.service.ts, libs/common/src/typings/Global.Interface.ts
/kind feature
This PR creates a vendor summary on the admin dashboard.
Fixes #
=> feature(admin): update admin vendor metrics with more summary data

apps/admin-gateway/src/module.api/dashboard.controller.ts, apps/users-service/src/users-service.controller.ts, apps/vendors-service/src/vendors.controller.ts, apps/vendors-service/src/vendors.service.ts, libs/common/src/typings/Global.Interface.ts, packages/sticky/libs/common/src/typings/index.ts
/kind packages
This PR creates the typings `OverviewStatI`, `DashboardStatI`, and `VendorStatI` in `@nana/sticky` package.
Fixes #
=> packages(sticky): create typings for overview, dashboard and vendor stats.

libs/common/src/dto/registerDriver.dto.ts
/kind fix
The `Length(min, ?max)` decorator is buggy. This PR creates a custom decorator to check if the NIN is exactly 11 digits.
Fixes #
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207065705443828
=> fix(drivers): create custom validator for nin validation

apps/admin-gateway/src/module.api/users.controller.ts
/kind fix
This PR fixes the`get-user` method in the admin gateway.
Fixes #
=> fix(admin): update http method to Get

packages/sticky/package.json
/kind packages
This PR updates @nana/sticky with the driver's NIN field in the schema and typings. With a sticky version release from `0.3.1` -> `0.3.2`.
Fixes #
=> chore(packages): bump sticky version 0.3.1 -> 0.3.2

apps/drivers-service/src/ODSA/odsa.service.ts
/kind fix
This PR fixes `getDriverStats`. Some values were returning `NaN`. This PR creates a filter to remove all `undefined` or `null` fields in the array and make calculations on fields that meet criteria.
Fixes #
=> fix(driver): fix driver stats NaN error

libs/common/src/database/dto/listing.dto.ts, libs/common/src/database/schemas/listings.cat.ts, libs/common/src/database/types/common.ts
=> chore(listings-service): Update listing category schema with nextDayDelivery field

packages/sticky/package.json
/kind chore
This PR bumps sticky version from 0.3.5 -> 0.3.6
Fixes #
=> chore(release): bump sticky version 0.3.5 -> 0.3.6

apps/users-service/src/users-service.service.ts
/kind chore
Uncomments the user signup slack notification.
Fixes #
=> chore(users-service): uncomment users slack message

apps/orders-service/src/main.ts, apps/payment-service/src/main.ts
=> fix(orders-service): fix cronjobs for orders and payments service

apps/drivers-service/src/ODSA/odsa.service.ts, apps/drivers-service/src/drivers-service.service.ts, apps/orders-service/src/main.ts, apps/payment-service/src/main.ts
/kind chore
Increase the `flagDriversOffline` cron to 30 minutes.
Fixes #
=> chore(drivers-service): update driver's flag

packages/sticky/package.json
/kind chore
This PR bumps the nana/sticky npm package version to `0.3.9`.
Fixes #
=> chore(release): bump sticky version 0.3.8 -> 0.3.9

apps/drivers-service/src/fleet/fleet.service.ts, libs/common/src/database/schemas/driver.schema.ts, libs/common/src/dto/fleet.dto.ts, libs/common/src/dto/registerDriver.dto.ts, packages/sticky/libs/common/src/dto/index.ts, packages/sticky/libs/common/src/schemas/index.ts, packages/sticky/package.json
/kind packages
This PR creates a schemas/dtos update for drivers in fleet organizations and releases a sticky update( version 0.4.2)
Fixes #
=> chore(packages): schemas/dtos + sticky update

apps/drivers-service/src/app.module.ts, apps/drivers-service/src/drivers-service.controller.ts, apps/drivers-service/src/fleet/fleet.controller.ts, apps/drivers-service/src/fleet/fleet.service.ts
/kind feature
This PR creates a feature that enables fleet owners to create automatically approved drivers.
Fixes #
=> feature(drivers-service): fleet owners creating approved drivers

apps/drivers-service/src/fleet/fleet.service.ts, libs/common/src/database/schemas/fleet-organization.schema.ts, packages/sticky/libs/common/src/schemas/index.ts
/kind feature
This PR updates the fleet organization schema with payment info.
Fixes #
=> feature(drivers-service): update schemas with payment info

apps/drivers-service/src/fleet/fleet.controller.ts, apps/drivers-service/src/fleet/fleet.service.ts
/kind feature
This PR enables Fleet owners to update the organization's information.
Fixes #
=> feature(drivers-service): fleet owner can update organization info

apps/drivers-service/src/app.module.ts, apps/drivers-service/src/fleet/fleet.controller.ts, apps/drivers-service/src/fleet/fleet.service.ts
/kind feature
This PR enables fleet owners to update organization logo/image.
Fixes #
=> feature(drivers-service): fleet owner can update organization logo

apps/drivers-service/src/fleet/fleet.controller.ts, apps/drivers-service/src/fleet/fleet.service.ts, libs/common/src/dto/fleet.dto.ts, packages/sticky/libs/common/src/dto/index.ts
/kind feature
This PR enables fleet members to update their profile (name. email and phone)
Fixes #
=> feature(drivers-service): fleet members can update their profile

apps/drivers-service/src/fleet/decorators/ownership.ts, apps/drivers-service/src/fleet/fleet.controller.ts, apps/drivers-service/src/fleet/fleet.service.ts
/kind feature
This PR creates populated members and enables members to get organization deliveries.
Fixes #
=> feature(drivers-service): members can fetch deliveries

packages/sticky/package.json
/kind packages
This PR bumps the sticky version to `0.4.3` which includes the `UpdateFleetMemberProfileDto` type.
Fixes #
=> chore(packages): bump sticky version 0.4.2 -> 0.4.3

apps/drivers-service/src/ODSA/odsa.service.ts, apps/drivers-service/src/drivers-service.controller.ts, apps/drivers-service/src/fleet/fleet.controller.ts, apps/drivers-service/src/fleet/fleet.service.ts
/kind feature
This PR enables a fleet member to assign a driver to a delivery.
Fixes #
=> feature(drivers-service): assign fleet driver

apps/drivers-service/src/fleet/fleet.service.ts
/kind fix
This PR fixes the `payload` omission by including a spread operator which passes the entire `payload` object to the repository creation method.
Fixes #
=> fix(drivers-service): fix email omission with spread operator

apps/drivers-service/src/fleet/fleet.controller.ts, apps/drivers-service/src/fleet/fleet.service.ts
/kind feature
This feature enables organization members to get fleet driver stats.
Fixes #
=> feature(drivers-service): member can get driver stats

apps/users-service/src/test/stubs/user.stub.ts, apps/users-service/src/users-service.service.ts, libs/common/src/database/schemas/users.schema.ts
/kind feature
This PR creates the address pin feature.
Fixes #
=> feature(users-service): address pin feature + tests fix

packages/sticky/libs/common/src/dto/index.ts, packages/sticky/libs/common/src/typings/index.ts, packages/sticky/package.json
/kind packages
This PR bumps the sticky version from `0.4.5` -> `0.4.6`.
Fixes #
=> chore(packages): bump sticky version 0.4.5 -> 0.4..6

apps/users-service/src/address-book-service.service.ts, apps/users-service/src/test/stubs/user.stub.ts, apps/users-service/src/users-service.service.ts, libs/common/src/database/schemas/address.book.schema.ts, libs/common/src/database/schemas/users.schema.ts, libs/common/src/database/types/common.ts, libs/common/src/typings/Global.Interface.ts, packages/sticky/libs/common/src/schemas/index.ts
/kind feature
This PR refactors the address pin to be attached to each Address Book object. pin is uniquely generated within(00000-99999) and query speed is improved with indexing.
Fixes #
=> feature(users-service): refactor address pin feature

.eslintrc, apps/drivers-service/src/fleet/fleet.controller.ts, apps/drivers-service/src/fleet/fleet.service.ts, libs/common/src/dto/registerDriver.dto.ts, libs/common/src/typings/Global.Interface.ts, packages/sticky/libs/common/src/dto/index.ts, packages/sticky/libs/common/src/schemas/index.ts, packages/sticky/libs/common/src/typings/index.ts
/kind fix
This PR fixes the array condition for organization stats, makes the `RegisterDriverDto` nin field optional and improves the conditions for organization creation.
Fixes #
=> fix(drrivers-service): array condition + driver dto + org conflicts

packages/sticky/libs/common/src/schemas/index.ts, packages/sticky/package.json
/kind packages
This PR bumps the internal npm package `sticky` from `0.4.8` -> `0.4.9`.
Fixes #
=> chore(packages): bump sticky version form 0.4.8 -> 0.4.9

apps/payment-service/src/payment.module.ts
/kind fix
Fixes build error due to missing mongo module import.
Fixes #
=> fix(payment-service): missing mongo module import

apps/orders-service/src/orders-service.service.ts, libs/common/src/database/schemas/order.schema.ts, libs/common/src/database/types/common.ts, libs/common/src/dto/PlaceOrder.dto.ts, libs/common/src/typings/Global.Interface.ts, packages/sticky/libs/common/src/dto/index.ts, packages/sticky/libs/common/src/typings/index.ts
/kind feature
This PR checks if the `fleetOrderType` is of `BOX` type. if `true` includes the `itemDescription` field in the `Order` object.
Fixes #
=> feature(orders-service): item description field for box package

apps/payment-service/src/fleets-payout/fleets-payout.service.ts
/kind fix
This PR fixes the payout computation bug. Initial deliveries didn't include the `driver` field. This PR includes a filter that checks for deliveries with the `driver` field.
Fixes #
=> fix(payments-service): filter existing deliveries with no driver field

apps/payment-service/src/coupons/coupon.service.ts
/kind feature
This PR deletes existing coupons that remain even after the validity period using a cron job.
Fixes #
=> feature(payment-service): delete expired coupons
